### ISSUE TITLE
pGenThreader.sh: Cannot copy $FSA 

### ISSUE THREAD

**Issue by skjoedt** [psipred/pGenTHREADER#3]
There is a spelling error in pGenThreader.sh when copying fasta file

``cp %FSA $JOB.fsa`` on line 34

should be

``cp $FSA $JOB.fsa``

One might consider not copying at all.

**Comment by DanBuchan** [comment]
I've corrected that. 

FWIW I would recommend using the GenThreader.sh script.

WRT to not copying, being able to pass in a per-job ID for the run allows you to run mutliple genthreader runs in an approximately threadsafe manner. Especially if you need to do something weird like run multiple genthreader runs over the same fasta file.
